language: python
python:
- '2.7'
- '3.5'
addons:
  apt_packages:
  - pandoc
install: pip install -r requirements.txt
script: true
deploy:
  provider: pypi
  user: bmweiner
  password:
    secure: igsWG2of9eiqRoYyCf6x+DmOchDd4ypxQhLOlsfy0SOuaNy25/M4n5GkgbOoY2pJhwd0Os8UoBbpmdoL5o9vlMrfBNQCUxom0/sYgxjHDrUJlZyRtm9U/gdu0VN83/vcz2a2tuLbi6zRKAGJfMosGN2ledrnRTMFTv0oRykVVb0QiWDwBpClqDyncKlepxv38gxdaVoL36r4FPVaqML2OnOuwdKdOOD3NIOP/+1ImOG1y63IqqEBhQ9IVB4jKJ1w4jHWNKSw82H12ra2o/0aJIGG8pmee1ZVpooyXnZpWUA5GVq0INPP3RHRZyxZmumD21AOvSKe7GuaffQJ7aj7Vx+kSTW89SWO2SEoB4W3CtI63w+yElLt0RxoKkpBkIPiw2SV3c1o69mGeHF252NEdaYZdjuvlezRPR4O8boii8hI0qDTGX3v3vy7Ha3zdn93K+v3xlCNeLxEFtxY9Y5c1ZsRjhr5uE24BL4pCwzImxlxvs0fX31NSim1D268tEidUk8jZCu6N3tjBl8c0Rf1u+inkuP3xLOoQgAwSTwsfVRFGkrLFhLwVL2bWoss9EWEyQMnGpjJROGHkCSR0BMl5aA7ux/b9He73lFk2QpmiV7KxMTlvOk5mNT/RDI+r2hQUjogVynEjY20gxKyjyV45FuhG/JFvXAKvdIXnnqDNmU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: bmweiner/jetpack
    condition: "$TRAVIS_PYTHON_VERSION = '2.7'"
env:
  global:
    secure: Eo1tTQHk/b29VVYA+8wUQhY1lgyYwVozoKomCRLkiazziDHxqlIQOSXH6WQYCyqkEQA30rVLI5VwD1VjOFH4Wq+7i3dkSCfO8SEGWM4Fe2KINS6U/4/QkEats4pvtAnsoCmri8ZotsveSsr3JvKxKjzzwUhMYanXdS8JkyMfqPmcBJucVt7BARlD8TmDwD/oJfxnLezaBTx/goywHIAsjcSlJawrtU+dBPfMWsIdvQgansWvcAY6VNGWCaefP+ojLzB0juWwn03ibW0eBzm27q1ux8p91pDllf5u4o0rS2guxXtiZtg9G2ICt0R4NDrskOIIAz1nPnAcvvkEzwZDLy8BeF1UJUSpIeqB+WCYnkZUm6D4/0S27AlpiSd1fW77QypwoYCMm9RQSr7Mw4YTY1wQgzwnrQKKiESXoFpBV1cjHk9HecyLfJGEsWon1L/B9+WOIz6jqeYBZXG4T0p4sb0YXBdLLpTNNvZftHEWWYhwTrmBQB5RcTp+UBzmhR/Y/6Ql6RV7Exvix9tg5o908k1ZNvSbwVzO3UFBtzmgdrcCLe9IbYswX/c3xlM4Z9/723NpqhVfHiP6diLDh/Oa9Ge1eTA3WT15xN503IB5zJR6IxS8vNo0j2wDLbjmxU8recrai8IHYoCRu68JxA/ADtkjeytnRCBdYI7ng6ozwM4=
